### ISSUE TITLE
UnauthorizedError: jwt issuer invalid. expected: undefined

### ISSUE THREAD

**Issue by dmongit** [auth0/nodejs-jwt-authentication-sample#32]
I followed instructions, and even tried changes shown in issue #30 because I was initially receiving the invalid audience error. Now I'm getting the invalid issuer error when I authenticate and try to hit a protected API. I'm using this example for my app: https://auth0.com/blog/adding-authentication-to-react-native-using-jwt/ 

Sign up and Login seem to work (aside from errors when I try to sign up the same user twice and try to login twice).

Any ideas?

I think the only difference is that my react-native app that uses this API as an end point fetches with my local IP instead of localhost.

Thanks!

**Comment by dmongit** [comment]
I'm not entirely sure how I resolved this. But, I got it working so it looks like it was something on my end. I changed the issuer to anything else. I changed my issuer to http://something.com and my username and password are both something in the user object. I'm not 100% if I changed anything else relevant b/c I was multitasking.

**Comment by JayathmaChathurangani** [comment]
This issue came for me when a forward slash was missing. I have used "https://user.auth0.com" which is wrong. Correct one is " "https://user.auth0.com/""

**Comment by josephkandi** [comment]
I get the same error. The error will go away when i remove the `issuer`. Is the `issuer` not supposed to be validated as well?

**Comment by dearamerican** [comment]
Have the same question! Is the `issuer` not supposed to be validated? Works for me when I remove it, but that doesn't seem like it should be the solution?

**Comment by dearamerican** [comment]
Ah, here it is: issuer should be 
```
`https://${process.env.AUTH0_DOMAIN}/`
```
if you just put ${process.env.AUTH0_DOMAIN} it will remain broken.

**Comment by stephanebruckert** [comment]
In my case I forgot .eu in my domain name

**Comment by Nabhag8848** [comment]
> Ah, here it is: issuer should be
> 
> ```
> `https://${process.env.AUTH0_DOMAIN}/`
> ```
> 
> if you just put ${process.env.AUTH0_DOMAIN} it will remain broken.

Thanks @dearamerican it worked
